"""empty message

Revision ID: 24e4e4f55f9a
Revises: 2822fa9db894
Create Date: 2024-01-05 20:34:55.897112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24e4e4f55f9a'
down_revision: Union[str, None] = '2822fa9db894'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parent_results', 'score',
               existing_type=sa.NUMERIC(precision=2, scale=1),
               type_=sa.FLOAT(precision=1),
               existing_nullable=True)
    op.drop_column('parent_results', 'foiz')
    op.alter_column('rules', 'one_true_answer',
               existing_type=sa.REAL(),
               type_=sa.FLOAT(precision=1),
               existing_nullable=True)
    op.alter_column('rules', 'one_false_answer',
               existing_type=sa.REAL(),
               type_=sa.FLOAT(precision=1),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rules', 'one_false_answer',
               existing_type=sa.FLOAT(precision=1),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('rules', 'one_true_answer',
               existing_type=sa.FLOAT(precision=1),
               type_=sa.REAL(),
               existing_nullable=True)
    op.add_column('parent_results', sa.Column('foiz', sa.NUMERIC(precision=2, scale=1), autoincrement=False, nullable=True))
    op.alter_column('parent_results', 'score',
               existing_type=sa.FLOAT(precision=1),
               type_=sa.NUMERIC(precision=2, scale=1),
               existing_nullable=True)
    # ### end Alembic commands ###
