"""empty message

Revision ID: 360376dfd615
Revises: 24e4e4f55f9a
Create Date: 2024-01-05 20:37:37.317251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '360376dfd615'
down_revision: Union[str, None] = '24e4e4f55f9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_number', sa.String(), nullable=True),
    sa.Column('group', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('parent_results', 'score',
               existing_type=sa.REAL(),
               type_=sa.FLOAT(precision=1),
               existing_nullable=True)
    op.alter_column('rules', 'one_true_answer',
               existing_type=sa.REAL(),
               type_=sa.FLOAT(precision=1),
               existing_nullable=True)
    op.alter_column('rules', 'one_false_answer',
               existing_type=sa.REAL(),
               type_=sa.FLOAT(precision=1),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rules', 'one_false_answer',
               existing_type=sa.FLOAT(precision=1),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('rules', 'one_true_answer',
               existing_type=sa.FLOAT(precision=1),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('parent_results', 'score',
               existing_type=sa.FLOAT(precision=1),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_table('classes')
    # ### end Alembic commands ###
