"""empty message

Revision ID: 8ba40a37c4b3
Revises: 
Create Date: 2024-01-01 22:42:46.542334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ba40a37c4b3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('books',
    sa.Column('books', sa.String(), nullable=True)
    )
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_number', sa.String(), nullable=True),
    sa.Column('group', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parent_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('who', sa.String(), nullable=True),
    sa.Column('farzand_sinfi', sa.String(), nullable=True),
    sa.Column('farzand_sinfi_guruxi', sa.String(), nullable=True),
    sa.Column('book', sa.String(), nullable=True),
    sa.Column('score', sa.NUMERIC(precision=2, scale=1), nullable=True),
    sa.Column('trues', sa.String(), nullable=True),
    sa.Column('falses', sa.String(), nullable=True),
    sa.Column('foiz', sa.NUMERIC(precision=2, scale=1), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('farzandi', sa.String(), nullable=True),
    sa.Column('farzand_sinf', sa.String(), nullable=True),
    sa.Column('farzand_sinf_guruxi', sa.String(), nullable=True),
    sa.Column('who', sa.String(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('a', sa.String(), nullable=True),
    sa.Column('b', sa.String(), nullable=True),
    sa.Column('d', sa.String(), nullable=True),
    sa.Column('true', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book', sa.Integer(), nullable=True),
    sa.Column('sovol', sa.Integer(), nullable=True),
    sa.Column('score', sa.FLOAT(), nullable=True),
    sa.Column('trues', sa.Integer(), nullable=True),
    sa.Column('falses', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rules',
    sa.Column('one_true_answer', sa.NUMERIC(precision=2, scale=1), nullable=True),
    sa.Column('one_false_answer', sa.NUMERIC(precision=2, scale=1), nullable=True),
    sa.Column('savollar', sa.Integer(), nullable=True)
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('sinfi', sa.String(), nullable=True),
    sa.Column('guruxi', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    op.drop_table('rules')
    op.drop_table('results')
    op.drop_table('questions')
    op.drop_table('parents')
    op.drop_table('parent_results')
    op.drop_table('classes')
    op.drop_table('books')
    op.drop_table('admins')
    # ### end Alembic commands ###
