"""empty message

Revision ID: b3fdfc087f01
Revises: d8d58223d3eb
Create Date: 2024-01-06 23:01:40.341664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3fdfc087f01'
down_revision: Union[str, None] = 'd8d58223d3eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent_results', sa.Column('id_raqam', sa.Integer(), nullable=False))
    op.drop_column('parent_results', 'id')
    op.alter_column('rules', 'one_true_answer',
               existing_type=sa.REAL(),
               type_=sa.FLOAT(precision=1),
               existing_nullable=True)
    op.alter_column('rules', 'one_false_answer',
               existing_type=sa.REAL(),
               type_=sa.FLOAT(precision=1),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rules', 'one_false_answer',
               existing_type=sa.FLOAT(precision=1),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('rules', 'one_true_answer',
               existing_type=sa.FLOAT(precision=1),
               type_=sa.REAL(),
               existing_nullable=True)
    op.add_column('parent_results', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('parent_results', 'id_raqam')
    # ### end Alembic commands ###
