"""empty message

Revision ID: bdee8bf1c8aa
Revises: 7b6a3e53d57d
Create Date: 2024-01-05 21:28:01.529461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdee8bf1c8aa'
down_revision: Union[str, None] = '7b6a3e53d57d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classes', 'group')
    op.alter_column('parent_results', 'score',
               existing_type=sa.REAL(),
               type_=sa.FLOAT(precision=1),
               existing_nullable=True)
    op.alter_column('rules', 'one_true_answer',
               existing_type=sa.REAL(),
               type_=sa.FLOAT(precision=1),
               existing_nullable=True)
    op.alter_column('rules', 'one_false_answer',
               existing_type=sa.REAL(),
               type_=sa.FLOAT(precision=1),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rules', 'one_false_answer',
               existing_type=sa.FLOAT(precision=1),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('rules', 'one_true_answer',
               existing_type=sa.FLOAT(precision=1),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('parent_results', 'score',
               existing_type=sa.FLOAT(precision=1),
               type_=sa.REAL(),
               existing_nullable=True)
    op.add_column('classes', sa.Column('group', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
