"""empty message

Revision ID: cee08f4b7e1e
Revises: 72ee62008508
Create Date: 2024-01-03 21:32:38.059476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cee08f4b7e1e'
down_revision: Union[str, None] = '72ee62008508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('chat_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'chat_id')
    # ### end Alembic commands ###
