"""empty message

Revision ID: e1bdd89e525a
Revises: a3074ea24c6d
Create Date: 2024-01-03 21:46:01.625308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1bdd89e525a'
down_revision: Union[str, None] = 'a3074ea24c6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book', sa.String(), nullable=True),
    sa.Column('sovol', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('trues', sa.Integer(), nullable=True),
    sa.Column('falses', sa.Integer(), nullable=True),
    sa.Column('score', sa.FLOAT(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    # ### end Alembic commands ###
